# Notebook 1 – Introduction to Machine Learning
Dataset - **retail transactions dataset** (`data.csv`).

## 1. What is Machine Learning?

**Machine Learning (ML)** is a branch of Artificial Intelligence in which a system learns patterns from data and improves its performance on a task **without being explicitly programmed** with fixed rules.

## 2. Why Machine Learning?

- Some problems are too complex for hand-written rules (e.g., recognizing handwriting, predicting customer churn).
- Data is growing rapidly, and ML can find patterns humans might miss.
- ML systems can **adapt and improve** as more data becomes available.
- Automates repetitive decision-making tasks (fraud detection, recommendations, forecasting).

## 3. AI vs ML vs Deep Learning

| Concept | Description |
|---|---|
| **Artificial Intelligence (AI)** | The broad science of building systems that mimic human intelligence (reasoning, perception, decision-making). |
| **Machine Learning (ML)** | A subset of AI where systems learn patterns from data instead of following explicit rules. |
| **Deep Learning (DL)** | A subset of ML that uses multi-layered neural networks to learn complex patterns, especially from images, text, and audio. |

**Relationship:** `AI ⊃ ML ⊃ Deep Learning`

## 4. Traditional Programming vs Machine Learning

| Traditional Programming | Machine Learning |
|---|---|
| `Rules + Data → Output` | `Data + Output → Rules (Model)` |
| Human writes the logic | Algorithm learns the logic from data |
| Works well for well-defined problems | Works well for complex, pattern-based problems |

Example: To detect spam emails traditionally, you'd write hundreds of if-else rules. In ML, you show the algorithm thousands of labeled spam/non-spam emails, and it learns the pattern itself.

## 5. Loading the Dataset

We'll use a real-world **online retail transactions dataset** to illustrate ML concepts throughout this notebook.

In [5]:
import pandas as pd
import numpy as np
df = pd.read_csv('data.csv', encoding='latin1')
print("Shape:", df.shape)
df.head()

Shape: (541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [ ]:
df.info()

In [6]:
df = df.dropna(subset=['CustomerID'])
df = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)]
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']
print("Shape after cleaning:", df.shape)
df.head()

Shape after cleaning: (397884, 9)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34

## 6. Supervised Learning

In **Supervised Learning**, the model learns from **labeled data** — each input example (features) has a known correct output (target/label).

The model learns a mapping: `Features → Target`

Common tasks: **Classification** and **Regression** (both covered below).

Example here: Using `Quantity` and `UnitPrice` (features) to predict `TotalPrice` (target) — a regression problem.

## 7. Unsupervised Learning

In **Unsupervised Learning**, the data has **no labels**. The model tries to find hidden structure or patterns in the data on its own.

Common task: **Clustering** — grouping similar data points together (e.g., grouping customers by purchasing behavior).

## 8. Semi-Supervised Learning

**Semi-Supervised Learning** uses a **small amount of labeled data** combined with a **large amount of unlabeled data** during training.

- Useful when labeling data is expensive or time-consuming (e.g., manually labeling millions of customer transactions as "fraud" vs "not fraud").
- The model first learns structure from the unlabeled data, then uses the few labeled examples to refine its understanding.

## 9. Reinforcement Learning

**Reinforcement Learning (RL)** is different from the above — there's no fixed dataset of features/labels. Instead:

- An **agent** interacts with an **environment**.
- It takes **actions**, receives **rewards or penalties**, and learns a **policy** to maximize cumulative reward over time.

Example: An RL agent could learn an optimal **dynamic pricing strategy** for our retail products — it tries different prices (actions), observes sales/profit (reward), and learns which pricing strategy maximizes revenue.

## 10. Classification

**Classification** is a supervised learning task where the target variable is **categorical** (a discrete class/label).

Example: Classify each transaction as **"High Value"** or **"Low Value"** based on `Quantity` and `UnitPrice`.

In [19]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
predictions = model.predict(X_test)
predictions

array([0, 1, 1, ..., 0, 0, 1], shape=(79577,))

## 11. Regression

**Regression** is a supervised learning task where the target variable is **continuous** (a numeric value).

Example: Predict `TotalPrice` from `Quantity` and `UnitPrice`.

In [22]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(predictions)

[0.49779417 0.49930764 0.4974689  ... 0.49697327 0.495988   0.50648966]

## 12. Clustering

**Clustering** is an unsupervised learning task that groups similar data points together **without predefined labels**.

Example: Group customers based on their **total spend** and **purchase frequency** (a simple customer segmentation).

In [10]:
from sklearn.cluster import KMeans
customer_df = df.groupby('CustomerID').agg(
    TotalSpend=('TotalPrice', 'sum'),
    PurchaseCount=('InvoiceNo', 'nunique')
).reset_index()
X_cluster = customer_df[['TotalSpend', 'PurchaseCount']]
kmeans_model = KMeans(n_clusters=3, random_state=42, n_init=10)
customer_df['Cluster'] = kmeans_model.fit_predict(X_cluster)
customer_df.head()

   CustomerID  TotalSpend  PurchaseCount  Cluster
0     12346.0    77183.60              1        2
1     12347.0     4310.00              7        0
2     12348.0     1797.24              4        0
3     12349.0     1757.55              1        0
4     12350.0      334.40              1        0

## 13. Core Machine Learning Terminology

Let's tie everything above back to the core vocabulary of ML, using our regression example (predicting `TotalPrice`) as reference.

### 13.1 Features

**Features** are the input variables used to make predictions.

Example: `Quantity`, `UnitPrice`

### 13.2 Target

The **Target** (also called the label) is the output variable the model is trying to predict.

Example: `TotalPrice` (regression) or `ValueClass` (classification)

### 13.3 Training

**Training** is the process of showing the model data so it can learn patterns.

Example: `model.fit(X_train, y_train)`

### 13.4 Prediction

**Prediction** is using the trained model to estimate the output for new/unseen data.

Example: `model.predict(X_test)`

### 13.5 Model

The **Model** is the mathematical representation learned from data that maps features to the target.

Example: `LinearRegression()`, `LogisticRegression()`, `KMeans()` objects

### 13.6 Parameters

**Parameters** are internal values the model **learns automatically** during training.

Example: Regression coefficients (`reg_model.coef_`), intercept (`reg_model.intercept_`)

### 13.7 Hyperparameters

**Hyperparameters** are configuration values **set before training** by the user, not learned from data.

Example: `n_clusters=3` in KMeans, `test_size=0.2` in train/test split